Still trying to make pydim wrapper Python3 ready.
I'm mostly using this:
http://python3porting.com/cextensions.html
and this:
https://docs.python.org/3/howto/cporting.html#module-initialization-and-state

Building the stuff with python3 seems to work now.
But the resulting module cannot be importet.

Error messages range
from:
No module named 'dimc'
   (
      while I was clearly able to verify the existence of the file:
      python3.4/site-packages/fact/dim/dimc.cpython-34m.so
   )

To:
ImportError: dynamic module does not define init function (PyInit_dimc)
    (
      while I was able to show with 'nm' that PyInit_dimc
      is contained in that .so-file:
      nm .local/lib/python3.4/site-packages/fact/dim/dimc.cpython-34m.so | grep dimc
      000000000000c8f0 T _Z11PyInit_dimcv
                             ^^^^^^^^^^^
    )

Usual discussions on stackoverflow, like these:
http://stackoverflow.com/questions/5041861/importerror-dynamic-module-does-not-define-init-function-but-it-does
https://github.com/rdkit/rdkit/issues/375

Did not help me....
Any ideas?